services:
  nginx:
    image: nginx # 1.25.3/mainline/latest, stable
    ports:
      - "80:80"
      # - "8080:8080" # other nginx ports
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_org/out:/out
